name: Code Check
on:
  push:
  workflow_call:

jobs:
  code-check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4

      - name: Install Turbo
        run: npm i -g turbo

      - name: Restore project deps
        run: npm ci

      - name: Lint check
        run: turbo lint

      - name: Code format check
        run: turbo format

      # FIXME: always fail on github action don;t know why
      # - name: Typescript check
      #   run: turbo typecheck
