name: Release

on:
  push:
    branches: [master, beta]

jobs:
  release:
    name: Release
    if: ${{ github.repository_owner == 'sawaYch' }}
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   deployments: write
    #   packages: write
    #   pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore dependencies
        run: npx ci

      - name: Install semantic-release extra plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git

      - name: Restore project deps
        run: npm ci

      - name: Build the package next-youtube-livechat
        run: cd packages/next-youtube-livechat && npm run build

      - name: Lint check
        run: npm run lint

      - name: Code format check
        run: npm run format

      - name: Typescript check
        run: npm run typecheck

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npx semantic-release
